### ISSUE TITLE
Does not compile: error[E0277]: the trait bound `midir::MidiOutputConnection: Connection` is not satisfied

### ISSUE THREAD

**Issue by ahcm** [mdwn/mtrack#50]
Compiling mtrack v0.1.6
error[E0277]: the trait bound `midir::MidiOutputConnection: Connection` is not satisfied
   --> /Users/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/mtrack-0.1.6/src/midi/midir.rs:149:29
    |
149 |                 connection: midir_connection,
    |                             ^^^^^^^^^^^^^^^^ the trait `Connection` is not implemented for `midir::MidiOutputConnection`
    |
    = help: the following other types implement trait `Connection`:
              ExcludeConnection<C>
              nodi::midir::MidiOutputConnection
note: required by a bound in `ExcludeConnection`

**Comment by mdwn** [comment]
Whoops! Let me take a look at this.

**Comment by mdwn** [comment]
So looks like this doesn't happen when building the source directly, but *does* happen when running `cargo install`. Thank you so much for letting me know! I'll fix this!

**Comment by mdwn** [comment]
Can you try running `cargo install --locked mtrack`?

Update: looks like this is an issue with the Cargo.lock file. Tonight I'm going to check in a few updates to the dependencies, regenerate the lock file, and cut a new release.

**Comment by ahcm** [comment]
Yes, with --locked it installed fine. Thanks!

I wanted to list devices on MacOS:
```
$ mtrack devices
Error: BackendSpecific { err: BackendSpecificError { description: "Invalid property value" } }
```

**Comment by mdwn** [comment]
I haven't tested this on MacOS outside of a few experiments. I've got a Mac I can test with, though. I'll file an issue to investigate MacOS support.

**Comment by mdwn** [comment]
https://github.com/mdwn/mtrack/issues/51

**Comment by mdwn** [comment]
This should be resolved. I'm going to close this and tag you on the other issue.

**Comment by ahcm** [comment]
v0.1.7 installed cleanly. See you in #51.
