### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by mdwn** [mdwn/mtrack#51]
Right now, mtrack is highly focused on Linux support. We should add MacOS support.

**Comment by mdwn** [comment]
@ahcm Could you describe your setup? MacOS version, audio interface, etc.? On MacOS 15.1.1, I'm getting the following when listing devices and a MOTU UltraLite-mk5 connected:

```
➜  ~ mtrack devices
Devices:
- MacBook Pro Speakers (Channels=2) (CoreAudio)
- UltraLite-mk5 (Channels=10) (CoreAudio)
```

**Comment by ahcm** [comment]
The error was caused by the wifi direct dongle that comes with AKG N9 hybrid.
Many USB DACs, I tested, cause the error, also over Bluetooth.
Some also work, notably an old RME Babyface, so maybe USB Audio Class 1 works and 2 not.

**Comment by mdwn** [comment]
Looking at the code, the listing function bails out on most errors. It should probably be less sensitive to them.

Another issue I've noticed is that mtrack tries to match the output format of the audio interface to the wav format. Most wav files seem to use integer samples. This seems to work fine on Linux, but most audio streams on Mac look to be floats. This can be addressed, but it needs to be done.

**Comment by mdwn** [comment]
@ahcm Would you be able to build and try https://github.com/mdwn/mtrack/pull/54? I was able to use this to list a Sabrent USB audio interface and play against the internal Mac speakers as well as a Behringer Wing.
